module.exports = {
  name: "AlphaFlux",
  tagline: "AI-Native Digital Growth",
  description: "AlphaFlux is an AI-native digital marketing agency that delivers superior results through the synthesis of deep human expertise and cutting-edge artificial intelligence. SEO, PPC, Social, Content, CRO, Email, Web Dev, AI/GEO, and Analytics.",
  url: "https://alphaflux.net",
  locale: "en_US",
  ga4: "", // DISABLED 2026-08-09: G-GZV90ZCT4E is Patriot Pest's property, NOT AlphaFlux. AlphaFlux ships analytics-off until David supplies its own GA4 ID.
  cacheBust: "v3",
  formSubmitInbox: "REPLACE_WITH_INBOX_EMAIL",
  author: {
    name: "David Patton",
    url: "https://alphaflux.net"
  },
  social: {
    linkedin: "https://linkedin.com/company/alphaflux",
    twitter: "https://twitter.com/alphaflux",
  },
  nav: [
    { label: "Services", url: "/services/" },
    { label: "Industries", url: "/industries/" },
    { label: "Case Studies", url: "/case-studies/" },
    { label: "Pricing", url: "/pricing/" },
    { label: "About", url: "/about/" },
    { label: "Blog", url: "/blog/" },
  ],
  footerServices: [
    { label: "AI Search & GEO", url: "/services/ai-geo/" },
    { label: "SEO", url: "/services/seo/" },
    { label: "PPC & Paid Media", url: "/services/ppc/" },
    { label: "Content Marketing", url: "/services/content/" },
    { label: "CRO", url: "/services/cro/" },
    { label: "Email Marketing", url: "/services/email/" },
    { label: "Web Development", url: "/services/web-development/" },
    { label: "Analytics", url: "/services/analytics/" },
    { label: "Creative", url: "/services/creative/" },
    { label: "Marketplace Ads", url: "/services/marketplace/" },
    { label: "Digital PR", url: "/services/digital-pr/" },
    { label: "Influencer", url: "/services/influencer/" },
    { label: "ASO", url: "/services/aso/" },
    { label: "Reputation", url: "/services/reputation/" },
    { label: "Automation", url: "/services/marketing-automation/" },
    { label: "Franchise", url: "/services/franchise/" },
    { label: "Free AI Visibility Audit", url: "/services/ai-geo/ai-visibility-audit/" },
  ],
  footerIndustries: [
    { label: "SaaS", url: "/industries/saas/" },
    { label: "eCommerce", url: "/industries/ecommerce/" },
    { label: "B2B", url: "/industries/b2b/" },
    { label: "Home Services", url: "/industries/home-services/" },
    { label: "Healthcare", url: "/industries/healthcare/" },
    { label: "Financial", url: "/industries/financial/" },
    { label: "Legal", url: "/industries/legal/" },
    { label: "Franchise", url: "/industries/franchise/" },
    { label: "Higher Education", url: "/industries/higher-education/" },
  ],
  footerCompany: [
    { label: "About", url: "/about/" },
    { label: "Case Studies", url: "/case-studies/" },
    { label: "Blog", url: "/blog/" },
    { label: "Contact", url: "/contact/" },
    { label: "Privacy Policy", url: "/legal/privacy/" },
    { label: "Terms of Service", url: "/legal/terms/" },
  ]
};
